name = input("whats your name?")
Age = int(input("How old are you?"))
color = input("What is your favorite color?")
address = input("Where do you live?")
first = float(input("1st number: "))
second = float(input("2nd number: "))
print(f"Hello, {name}! You are {Age} years old.")
print(f"Next year you will be {Age + 1}.")
print(f"Your favorite color is {color} and you live in {address}.")
print(f"The sum of {first} and {second} is {first + second}.")
print(f"The difference between {first} and {second} is {first - second}.")
print(f"The product of {first} and {second} is {first * second}.")
print(f"The quotient of {first} and {second} is {first / second}.")